# Generated by Django 3.1.4 on 2020-12-15 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Name')),
                ('column_separator', models.CharField(choices=[('comma', ','), ('semicolon', ';')], max_length=20, verbose_name='Column separator')),
                ('string_character', models.CharField(choices=[('double_quot', '"'), ('single_quot', "'")], max_length=20, verbose_name='String character')),
            ],
        ),
        migrations.CreateModel(
            name='SchemaColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=120, verbose_name='Column name')),
                ('column_type', models.CharField(choices=[('full_name', 'Full name'), ('job', 'Job'), ('email', 'Email'), ('domain', 'Domain name'), ('phone_num', 'Phone number'), ('company', 'Company name'), ('text', 'Text'), ('int', 'Integer'), ('address', 'Address'), ('date', 'Date')], max_length=50, verbose_name='Type')),
                ('range_from', models.IntegerField(blank=True, verbose_name='From')),
                ('range_to', models.IntegerField(blank=True, verbose_name='To')),
                ('order', models.IntegerField(unique=True, verbose_name='Order')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schemas.schema')),
            ],
        ),
    ]
