# Generated by Django 3.1.4 on 2020-12-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemacolumn',
            name='range_from',
            field=models.IntegerField(blank=True, null=True, verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='schemacolumn',
            name='range_to',
            field=models.IntegerField(blank=True, null=True, verbose_name='To'),
        ),
    ]
