# Generated by Django 3.1.4 on 2020-12-15 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0003_auto_20201215_2038'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='schemacolumn',
            name='unique chapter',
        ),
        migrations.AddConstraint(
            model_name='schemacolumn',
            constraint=models.UniqueConstraint(fields=('schema', 'order'), name='unique order'),
        ),
    ]
