# Generated by Django 3.1.4 on 2020-12-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0004_auto_20201215_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemacolumn',
            name='order',
            field=models.IntegerField(verbose_name='Order'),
        ),
    ]
