# Generated by Django 3.1.4 on 2020-12-15 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0005_auto_20201215_2042'),
    ]

    operations = [
        migrations.AddField(
            model_name='schema',
            name='modified_date',
            field=models.DateField(auto_now=True, verbose_name='Modified'),
        ),
    ]
