# Generated by Django 3.1.4 on 2020-12-19 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0006_schema_modified_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchemaDataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now=True, verbose_name='Created')),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('processing', 'Processing')], max_length=20, verbose_name='Status')),
                ('link', models.CharField(blank=True, max_length=120, null=True, verbose_name='link')),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schemas.schema')),
            ],
        ),
    ]
