# Generated by Django 3.1.4 on 2020-12-20 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0007_schemadataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemadataset',
            name='rows_quantity',
            field=models.IntegerField(null=True, verbose_name='rows_quantity'),
        ),
        migrations.AlterField(
            model_name='schema',
            name='column_separator',
            field=models.CharField(choices=[(',', 'Coma (,)'), (';', 'Semicolon (;)')], max_length=20, verbose_name='Column separator'),
        ),
        migrations.AlterField(
            model_name='schema',
            name='string_character',
            field=models.CharField(choices=[('"', 'Double quot (")'), ("'", "Single quot (')")], max_length=20, verbose_name='String character'),
        ),
        migrations.AlterField(
            model_name='schemadataset',
            name='status',
            field=models.CharField(choices=[('ready', 'Ready'), ('processing', 'Processing')], default='processing', max_length=20, verbose_name='Status'),
        ),
    ]
