# Generated by Django 3.1.4 on 2020-12-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemas', '0008_auto_20201220_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='schemadataset',
            name='task_id',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='task_id'),
        ),
    ]
